### ISSUE TITLE
Google 插件配置显示不全

### ISSUE THREAD

**Issue by shenweiyan** [rcy1314/nav-manage#1]
如图所示，配置里面的内容左右都被覆盖住了：

![17275724876271](https://github.com/user-attachments/assets/ee178d32-453b-452a-be30-e4d8ebab005d)

**Comment by rcy1314** [comment]
@shenweiyan 感谢反馈，不过我这边都是全的，测试用的Edge浏览器和Google浏览器，不过我的是MAC系统，后续会再调整优化

**Comment by shenweiyan** [comment]
> @shenweiyan 感谢反馈，不过我这边都是全的，测试用的Edge浏览器和Google浏览器，不过我的是MAC系统，后续会再调整优化

我用的是 Win 10 22H2 专业版 + Chrome 版本 129.0.6668.71（正式版本）（64 位）

**Comment by rcy1314** [comment]
@shenweiyan 已提交修复，测试了下你指的应该是搜索后弹出的结果界面超出部分显示的问题，我这边因为只有MAC，测试原始的界面（设置的为220px的宽度是正常的，如果你的不正常可以再修改这个宽度，但过宽后会影响界面美观），搜索的界面BUG可以等待扩展商店审核通过后再安装测试，或者点击下载开发版修改调试
[Nav-manage-extension.zip](https://github.com/user-attachments/files/17197951/Nav-manage-extension.zip)
<img width="476" alt="1727744179408" src="https://github.com/user-attachments/assets/69bc7eb0-850d-484e-aabe-b84960ef39d4">

**Comment by shenweiyan** [comment]
测试了一下，发现 Win10 需要 `width: 250px` 才能显示完全。
![20241008 093605](https://github.com/user-attachments/assets/373e2b30-760a-4a8f-bbbc-ab7fbc75ecb2)

**Comment by rcy1314** [comment]
@shenweiyan 由于我没有win，不能实际测试。不过如果是这样可以设置增加css参数max-width为250px或者css单独设置不同尺寸的适配，下次调整会再加上，不过还未想好要不要再在扩展中添加其他的选项

**Comment by rcy1314** [comment]
@shenweiyan 已提交测试V1.3，代码变更如下，你可以测试是否正常
CSS:

```
body {
            font-family: Arial, sans-serif;
            background-color: #1a1a1a;
            color: white;
            padding: 15px;
            margin: 0;
            display: flex;
            flex-direction: column;
            justify-content: center; /* 垂直居中 */
            align-items: center;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            overflow: hidden; /* 防止溢出 */
        }
    
        .mac {
            width: 220px;
        }
        .win {
            width: 250px; /* 或者你想要的其他值 */
        }
```

JS:

```
<script>
        // 检测操作系统
        const isMac = navigator.platform.toUpperCase().includes('MAC');
        const isWin = navigator.platform.toUpperCase().includes('WIN');

        // 根据操作系统添加相应的类
        if (isMac) {
            document.body.classList.add('mac');
        } else if (isWin) {
            document.body.classList.add('win');
        }
    </script>
```
